const $ = s => document.querySelector(s);
const uid = () => crypto.randomUUID();
const section = (title, instructions='') => ({id:uid(),title,instructions});
const defaults = [
  {id:'brightside-followup',name:'Brightside Follow-Up',sections:[section('Presenting Issues','Five sentences, paragraph form. Describe current issues and assessment; use direct quotes where applicable.'),section('Functional Impairment Domains','Identify only supported domains: Vocational, Social, Interpersonal, Academic, Daily Living, Independence.'),section('Severity of Impairment','Use Mild, Moderate, Marked, or Severe only if supported by the transcript; otherwise leave blank.'),section('Functional Impairment Description','Paragraph form; describe concrete effects on functioning.'),section('Response to Treatment','Paragraph describing documented interventions and the client’s response.')]},
  {id:'brightside-initial',name:'Brightside Initial Session',sections:['Mental Health Symptoms (onset, duration, frequency)','Previous Episodes','Relevant Childhood, Family, Social, Educational, Occupational and Legal History','Family Functioning','Relevant Cultural Background, Identity and Diversity Considerations','Strengths, Interests and Leisure Activities','Previous Suicide Attempts','Previous or Current Self-Injury Behavior','Psychiatric Hospitalization History','Family History of Mental Health or Substance Use Disorders','Trauma, Abuse, Neglect or Exploitation','Current Alcohol Use, Substance Use, Gambling or Other Addictive Behaviors','Tobacco or Nicotine Use','Diagnosis Established in Source'].map(t=>section(t,t==='Diagnosis Established in Source'?'Only repeat a diagnosis explicitly established in the transcript; never infer one.':'Concise paragraph narrative. Leave blank if not discussed.'))},
  {id:'grow-followup',name:'Grow Follow-Up',sections:['Focus of the Session / Topics Discussed','Client Reported Symptom Frequency','Impact on Functioning','Therapist Interventions Used','Client Response to Interventions','Client Actions Outside Sessions Toward Goals'].map(t=>section(t,'Thorough clinical paragraph narrative, limited to what the transcript supports.'))},
  {id:'summarize',name:'Summarize',sections:[section('Session Summary','Thorough narrative of the session, including concerns, symptoms, functioning, relevant context and clinically meaningful themes.'),section('Interventions Used','Include only interventions actually documented.'),section('Client Response','Describe stated or observed response when documented.'),section('Progress and Barriers','Include only supported progress and barriers.'),section('Plan and Homework','Include only plans and homework explicitly discussed.'),section('Risk Discussed','Include only risk content explicitly discussed, faithfully and without extrapolation.')]}
];
const safeParse=(s,f)=>{try{return JSON.parse(s)||f}catch{return f}};
let templates=safeParse(localStorage.getItem('noteTemplatesV1'),defaults);
let files=[];let selected=null;let view='workspace';let editing=templates[0].id;
const save=()=>localStorage.setItem('noteTemplatesV1',JSON.stringify(templates));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const current=()=>files.find(f=>f.id===selected);
const template=id=>templates.find(t=>t.id===id)||templates[0];
const optionList=id=>templates.map(t=>`<option value="${esc(t.id)}" ${id===t.id?'selected':''}>${esc(t.name)}</option>`).join('');
function render(){
 $('#app').innerHTML=`<header><div><div class="brand">Session Notes</div><div class="sub">Local clinical drafting workbench</div></div><nav><button class="${view==='workspace'?'active':''}" data-nav="workspace">Workspace</button><button class="${view==='templates'?'active':''}" data-nav="templates">Templates</button></nav></header><main class="wrap"><div class="intro"><div><h1>${view==='workspace'?'Draft session notes':'Edit note templates'}</h1><p>${view==='workspace'?'Review every draft against its transcript before use.':'Changes are saved in this browser on this computer.'}</p></div><span class="badge">Local workflow</span></div>${view==='workspace'?workspace():templatesView()}</main>`;
 document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{view=b.dataset.nav;render()});
 if(view==='workspace') bindWorkspace(); else bindTemplates();
}
function workspace(){let f=current(),t=f&&template(f.templateId);return `<div class="workspace"><div class="panel"><div class="panelhead"><h2>Sessions <span class="muted">${files.length}</span></h2></div><div class="panelbody"><div class="drop" id="drop">＋<strong>Drop transcripts here</strong><small>or click to choose .txt, .docx, .pdf</small><input id="pick" type="file" multiple accept=".txt,.docx,.pdf" hidden></div><div class="queue">${files.map(x=>`<div class="file ${x.id===selected?'selected':''}" data-file="${x.id}"><div class="row space"><strong title="${esc(x.name)}">${esc(x.name)}</strong><button class="danger" data-remove="${x.id}" title="Remove">×</button></div><select data-select="${x.id}" aria-label="Note type for ${esc(x.name)}">${optionList(x.templateId)}</select><div class="status">${esc(x.status)}</div></div>`).join('')}</div></div></div><div class="panel"><div class="panelhead"><h2>Transcript</h2><span class="muted">${f?`${f.text.length.toLocaleString()} characters`:''}</span></div><div class="panelbody">${f?`<textarea class="transcript" id="transcript" aria-label="Transcript">${esc(f.text)}</textarea>`:'<div class="empty">Add a transcript to begin.</div>'}</div></div><div class="panel"><div class="panelhead"><h2>${t?esc(t.name):'Draft note'}</h2><div class="toolbar">${f?'<button id="generate">Generate draft</button><button id="copyall" class="secondary">Copy all</button>':''}</div></div><div class="note-scroll">${f?`<div class="notice">AI output is a draft. Check identity removal, quotes, risk language, and unsupported claims before copying.</div>${t.sections.map(s=>`<div class="section"><div class="sectionhead"><span>${esc(s.title)}</span><button class="secondary" data-copy="${s.id}">Copy</button></div><textarea data-output="${s.id}" aria-label="${esc(s.title)}">${esc(f.output[s.id]||'')}</textarea></div>`).join('')}`:'<div class="empty">Select a session to view its note sections.</div>'}</div></div></div>`}
function bindWorkspace(){let drop=$('#drop'),pick=$('#pick');drop.onclick=()=>pick.click();pick.onchange=e=>addFiles(e.target.files);drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');addFiles(e.dataTransfer.files)};
 document.querySelectorAll('[data-file]').forEach(el=>el.onclick=()=>{selected=el.dataset.file;render()});document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=e=>{e.stopPropagation();files=files.filter(f=>f.id!==el.dataset.remove);if(selected===el.dataset.remove)selected=files[0]?.id||null;render()});document.querySelectorAll('[data-select]').forEach(el=>el.onchange=e=>{e.stopPropagation();let f=files.find(x=>x.id===el.dataset.select);f.templateId=el.value;f.output={};render()});
 let f=current();if(!f)return;$('#transcript').oninput=e=>{f.text=e.target.value};document.querySelectorAll('[data-output]').forEach(el=>el.oninput=e=>f.output[el.dataset.output]=e.target.value);document.querySelectorAll('[data-copy]').forEach(el=>el.onclick=()=>copy(f.output[el.dataset.copy]||'',el));$('#copyall').onclick=()=>copy(template(f.templateId).sections.filter(s=>f.output[s.id]?.trim()).map(s=>`${s.title}\n${f.output[s.id]}`).join('\n\n'),$('#copyall'));$('#generate').onclick=()=>generate(f);
}
async function copy(value,el){if(!value.trim())return;try{await navigator.clipboard.writeText(value);let old=el.textContent;el.textContent='Copied';setTimeout(()=>el.textContent=old,1300)}catch{alert('Clipboard access was blocked. Select and copy the text manually.')}}
async function addFiles(list){for(const file of list){let f={id:uid(),name:file.name,text:'',templateId:templates[0].id,output:{},status:'Reading…'};files.push(f);selected=f.id;render();try{let data=await new Promise((resolve,reject)=>{let reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});let response=await fetch('/extract',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:file.name,data})});let result=await response.json();if(!response.ok)throw Error(result.error);f.text=result.text;f.status='Ready'}catch(e){f.status='Error: '+e.message}render()}}
async function generate(f){if(!f.text.trim())return alert('Add transcript text first.');if(Object.values(f.output).some(v=>v.trim())&&!confirm('Replace the current draft for this session?'))return;f.status='Generating…';render();try{let response=await fetch('/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transcript:f.text,template:template(f.templateId)})});let result=await response.json();if(!response.ok)throw Error(result.error);f.output=result.sections;f.status='Draft ready — review required'}catch(e){f.status='Generation error: '+e.message}render()}
function templatesView(){let t=template(editing);return `<div class="template-grid"><div class="panel panelbody template-list"><h2>Note types</h2>${templates.map(x=>`<button class="${x.id===t.id?'active':''}" data-edit="${x.id}">${esc(x.name)}</button>`).join('')}<button id="addtemplate">＋ New template</button></div><div class="panel panelbody"><label class="field">Template name<input id="tname" value="${esc(t.name)}"></label><h2>Sections <span class="muted">${t.sections.length}</span></h2><div id="sections">${t.sections.map((s,i)=>`<div class="editsection" data-section="${s.id}"><div class="row space"><strong>Section ${i+1}</strong><div class="toolbar"><button class="secondary" data-up="${s.id}" ${i===0?'disabled':''}>↑</button><button class="secondary" data-down="${s.id}" ${i===t.sections.length-1?'disabled':''}>↓</button><button class="danger" data-delete="${s.id}">Remove</button></div></div><label class="field">Heading<input data-title="${s.id}" value="${esc(s.title)}"></label><label class="field">Instructions<textarea data-instructions="${s.id}">${esc(s.instructions)}</textarea></label></div>`).join('')}</div><div class="template-actions"><button id="addsection">＋ Add section</button><button id="savetemplate" class="secondary">Save changes</button><button id="resettemplate" class="secondary">Restore all original templates</button></div><p class="muted" style="margin-top:14px">Blank sections can be left empty in a generated note. Templates are stored locally in this browser.</p></div></div>`}
function bindTemplates(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=b.dataset.edit;render()});$('#tname').onchange=e=>{template(editing).name=e.target.value.trim()||'Untitled';save();render()};document.querySelectorAll('[data-title]').forEach(el=>el.onchange=()=>{template(editing).sections.find(s=>s.id===el.dataset.title).title=el.value;save();render()});document.querySelectorAll('[data-instructions]').forEach(el=>el.onchange=()=>{template(editing).sections.find(s=>s.id===el.dataset.instructions).instructions=el.value;save()});$('#addsection').onclick=()=>{template(editing).sections.push(section('New section'));save();render()};$('#addtemplate').onclick=()=>{let t={id:uid(),name:'New template',sections:[section('Session Summary')]};templates.push(t);editing=t.id;save();render()};$('#savetemplate').onclick=()=>{save();alert('Template saved locally.')};$('#resettemplate').onclick=()=>{if(confirm('Replace all edited templates with the four original note types?')){templates=defaults;editing=templates[0].id;save();render()}};document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{let t=template(editing);if(t.sections.length<2)return alert('Keep at least one section.');t.sections=t.sections.filter(s=>s.id!==b.dataset.delete);save();render()});for(let direction of ['up','down'])document.querySelectorAll(`[data-${direction}]`).forEach(b=>b.onclick=()=>{let a=template(editing).sections,i=a.findIndex(s=>s.id===b.dataset[direction]),j=i+(direction==='up'?-1:1);[a[i],a[j]]=[a[j],a[i]];save();render()})}
render();
